### ISSUE TITLE
Wrong variable name used - qr-code example

### ISSUE THREAD

**Issue by cwlind** [googleworkspace/add-ons-samples#66]
In file [qr-code/src/main.js](https://github.com/googleworkspace/add-ons-samples/blob/master/qr-code/src/main.js) 

Line 116:  variable _content_ should be _html_.

The variable _html_  is declared on line 114, but never used. Code is broken as is, but changing the variable to _html_ fixes the Addon.

**Comment by sqrrrl** [comment]
Fixed via #65
